wagtail/wagtailtrans

.dockerignore, CONTRIBUTING.md, README.rst
1. We have removed the Docker file earlier, removed the .dockerignore file as well.
2. Fixed some style notation and typos in the README + Contributing
=> Some cleanup & typo fixes

src/wagtailtrans/forms.py, tests/unit/test_forms.py
Add a check for an existing default language before setting default to False..
=> Save first language default

Makefile, setup.py, src/wagtailtrans/managers.py, src/wagtailtrans/models.py, src/wagtailtrans/signals.py, src/wagtailtrans/urls/languages.py, src/wagtailtrans/urls/translations.py, src/wagtailtrans/wagtail_hooks.py, tests/unit/test_models.py, tox.ini
Some cleanup of the codebase, ready for next release
=> Release b2

README.rst, docs/conf.py, setup.py
Add documentation to Read The Docs
http://wagtailtrans.readthedocs.io/en/latest/index.html
=> Implement rtd

README.rst
=> More obvious docs link in README

docs/getting_started.rst
Minor import issue, since `wagtail.wagtailstrans` isn't a valid import path
=> Fix invalid import of wagtailtrans

.coveragerc, setup.py, src/wagtailtrans/__init__.py
=> Add VERSION in setup.py and package init

src/wagtailtrans/config.py, src/wagtailtrans/forms.py, src/wagtailtrans/permissions.py, src/wagtailtrans/signals.py, src/wagtailtrans/templatetags/translations_wagtail_admin.py, src/wagtailtrans/utils/conf.py, src/wagtailtrans/wagtail_hooks.py, tests/unit/utils/test_conf.py
Since our codebase is starting to get bigger and settings are added, I've refactored all the default settings (which got brutally set in the `AppConfig`) to a `get_wagtailtrans_setting` which will lookup it's default value in dict defined in `wagtailtrans.utils.conf`. 
This approach is more in line with the other wagtail addons created by Lukkien.
=> Settings cleanup

MANIFEST.in, src/wagtailtrans/models.py
=> fix default language issues

docs/source/migrating.rst
=> Add missing comma to migration example

src/wagtailtrans/middleware.py, tests/unit/test_middleware.py
I thought it would be nice if the middleware would take in account the `Accept-Language` received from the browsers.
=> Listen to Accept-Language

.travis.yml, tox.ini
By adding Wagtail 1.8 we have a failing test on the issue mentioned in #58
=> Add wagtail 1.8 to the tox and travis suite

.gitignore, src/wagtailtrans/edit_handlers.py, src/wagtailtrans/forms.py, src/wagtailtrans/models.py, src/wagtailtrans/urls/translations.py, src/wagtailtrans/views/translation.py, src/wagtailtrans/wagtail_hooks.py, tests/conftest.py, tests/factories/requests.py, tests/factories/users.py, tests/fixtures.py, tests/unit/test_views.py
Implemented a ``wagtailadmin.views.generic.CreateView`` for creating translations when ``WAGTAILTRANS_SYNC_TREE = False``.
This should fix #58 and brings support for wagtail 1.8
=> Form _meta issue

.codecov.yml, .travis.yml, README.rst
To keep this in-sync with Wagtails point-of-view.
=> Use codecov instead of coveralls

docs/source/reference/index.rst, docs/source/reference/templatetags.rst, src/wagtailtrans/sites.py, src/wagtailtrans/templates/wagtailtrans/templatetags/language_selector.html, src/wagtailtrans/templatetags/wagtailtrans_tags.py, tests/_sandbox/pages/templates/base.html, tests/_sandbox/pages/templates/pages/home_page.html, tests/unit/test_sites.py, tests/unit/test_templatetags.py
This PR will introduce 2 new template tags:
- assignment tag for getting the translation urls
- inclusion tag to render a language selector
=> Add language selector template tags

CHANGELOG.rst, CONTRIBUTORS.rst, src/wagtailtrans/templatetags/wagtailtrans_tags.py, tests/factories/pages.py, tests/unit/test_templatetags.py
=> update language selector templatetag

CONTRIBUTORS.rst, tests/unit/test_templatetags.py
Unittest for wagtailtrans admin templatetags.
#81
=> Unittest for admin templatetags

src/wagtailtrans/models.py
=> Fix docstring for rootpage serve method

CONTRIBUTORS.rst, Makefile, src/wagtailtrans/managers.py, src/wagtailtrans/middleware.py, src/wagtailtrans/models.py, tests/unit/test_edit_handlers.py, tests/unit/test_models.py, tests/unit/test_permissions.py
=> Default Language for site in middleware

docs/source/getting_started.rst, docs/source/migrating.rst, tests/_sandbox/pages/migrations/0001_initial.py, tests/_sandbox/pages/models.py
=> suggestion for changing the docs

docs/source/getting_started.rst
=> Fix settings name

.travis.yml, docs/source/getting_started.rst, src/wagtailtrans/middleware.py, src/wagtailtrans/models.py, tests/_sandbox/settings/base.py, tests/factories/requests.py, tests/unit/test_middleware.py, tests/unit/test_models.py, tox.ini
Preparing for the official deprecation of the SiteMiddleware
=> Backwards compatible SiteMiddleware
