- src/wagtailtrans/__init__.py
- tests/_sandbox/settings/base.py
With this setting, it doesn't matter where you put `wagtailtrans` in your `INSTALLED_APPS`, wagtail templates will be overridden by wagtailtrans.
```
from wagtailtrans import WAGTAILTRANS_TEMPLATE_DIR
TEMPLATES = {
'DIRS': [
WAGTAILTRANS_TEMPLATE_DIR,
]
}
```
> Add setting for the template dir (allow overrides)

- CHANGELOG.rst
- src/wagtailtrans/models.py
- src/wagtailtrans/signals.py
- src/wagtailtrans/urls/translations.py
- src/wagtailtrans/wagtail_hooks.py
- tests/unit/test_models.py
The include_self property of TranslatablePage.get_translations isn't required for wagtailtrans to work. Previously we used it for the `translate into` button, since the object (page) itself isn't required in this list we can remove it.
> Remove the include_self property of the get_translations method

- src/wagtailtrans/edit_handlers.py
- src/wagtailtrans/models.py
- src/wagtailtrans/signals.py
- tests/unit/test_models.py
When publishing pages with the setting `LANGUAGES_PER_SITE=True` it always forced the page to become the `default_language` for that site.
> Force the parent language only when the parent has a language

- src/wagtailtrans/models.py
A fix for when LANGUAGE_PER_SITE is enabled and you move a page. (did not move pages with a default language other than the database default language)
> Fix move language per site

- .travis.yml
- README.rst
- setup.py
- src/wagtailtrans/migrations/0004_sitelanguages.py
- tox.ini
I've fixed a minor issue, where migrating with a wagtail 1.6 installation wouldn't work, because we were pointing to a newer migration than available in wagtail 1.6
Also updated the tox.ini and travis config to test against wagtail 1.6 and wagtail 1.7
> Wagtail 16 support

- docs/source/migrating.rst
there was a typo in a table name, which was referenced in the SQL section of the example migration in the docs
> Fix "wagatail..." typo in migration example

- src/wagtailtrans/templatetags/translations_wagtail_admin.py
This switches to assignment tags to make code compatible with Django 1.8
@mikedingjan Needs review, this does imply using the slightly deprecated assignment tags..
> Switch to assignment tags for django 1.8 compatibility

- src/wagtailtrans/models.py
As described in issue #54 sometimes a page instance can show up as not a `TranslatablePage` instance, this should fix that.
> Add specific in the AdminTranslatablePageForm to fix issue 54

- docs/source/getting_started.rst
wagtailtrans.middleware.TranslationMiddleware tries to access request.site,
which is only available if wagtail.wagtailcore.middleware.SiteMiddleware is
loaded first. Since django will happily and silently let the AttributeError
pass, this should really be documented
> Document middleware dependency

- src/wagtailtrans/middleware.py
- tests/unit/test_middleware.py
This will fix issues when starting a new project which doesn't have any ``Language`` objects in it's database.
> Update middleware to prevent errors on empty database

- .travis.yml
Right now the coveralls bot has spammy behaviour in Pull Requests. Unfortunately the `after_success` gets executed after every successful step in the build matrix. At some point in time an `after_all` command will be available. See: https://github.com/travis-ci/travis-ci/issues/929
For now I have added a workaround: https://github.com/alrra/travis-after-all
> Less spammy coveralls

- .travis.yml
- README.rst
- tox.ini
As agreed on, we're only supporting the current and 2 previous versions of wagtail. This PR drops the tests for wagtail 1.6 and add tests for wagtail 1.9
> Drop wagtail 1.6, add tests for wagtail 1.9

- .travis.yml
- CHANGELOG.rst
- README.rst
- setup.cfg
- tests/_sandbox/settings/base.py
- tox.ini
This PR will:
- Add support for Python 3.6, Wagtail 1.10 and Django 1.11
- Remove support for Wagtail 1.7 and Django 1.9
Fixes: #82 and #84
> Update tox and travis test matrix in-line with Wagtail

- src/wagtailtrans/templatetags/translations_wagtail_admin.py
Cleaned up the templatetag for language_per_site_enabled within our wagtailadmin tags.
Whilst prepping some additional templatetag tests it turned out this templatetag is not used anywhere. Or maybe I'm missing something obvious 😉
> Cleanup templatetag for language_per_site_enable

- src/wagtailtrans/signals.py
- src/wagtailtrans/sites.py
- tests/factories/language.py
- tests/factories/pages.py
- tests/unit/test_signals.py
- tests/unit/test_sites.py
fix a bug where non translatable pages will crash the signal triggered when creating a new language
> Fix bug which when creating new language if there are non translatable languages in the tree

- src/wagtailtrans/models.py
- tests/_sandbox/settings/base.py
- tests/unit/test_models.py
- tests/unit/test_views.py
Their is a issue with WAGTAILTRANS_LANGUAGES_PER_SITE setting, when it is set to True, we then  get a KeyError: u'is_default'. You don't even need to delete the is_default field, when it isn't even added to the FieldPanel, it wont show, The field is a boolean field that is set to false. So when you create a language it will pass without problems.
> fix issue with WAGTAILTRANS_LANGUAGES_PER_SITE SETTING

- .travis.yml
- appveyor.yml
- tox.ini
- Add Wagtail 1.12 to the testsuite. 
- Trim down Wagtail 1.9 tests.
> Add tests for Wagtail 1.12

- .travis.yml
- CHANGELOG.rst
- README.rst
- appveyor.yml
- docs/source/getting_started.rst
- docs/source/releases/0.2.rst
- setup.py
- src/wagtailtrans/__init__.py
- src/wagtailtrans/models.py
- src/wagtailtrans/templatetags/translations_wagtail_admin.py
- src/wagtailtrans/urls/translations.py
- src/wagtailtrans/views/translation.py
- tests/_sandbox/settings/base.py
- tests/unit/test_models.py
- tests/unit/test_views.py
- tox.ini
> Cleanup for Wagtail 1.12 support

- CONTRIBUTORS.rst
- src/wagtailtrans/middleware.py
- tests/unit/test_middleware.py
This PR should add a preferred language cookie in the browser on each request.
The checking for a language is now as follows:
1. path
2. cookie
3. browser accept headers
4. default site language from wagtailtrans
5. default language in settings
> Remember language preference in cookie

- docs/source/settings.rst
- src/wagtailtrans/conf.py
- src/wagtailtrans/wagtail_hooks.py
This allows the CMS editor to only see the tree of the canonical
language but also lets the user edit the page in the different
laganguages.
> Add a HIDE_TRANSLATION_TREES setting with an edit in button

- docs/source/settings.rst
- src/wagtailtrans/signals.py
When using loaddata to load a database dump we don't want to
automatically create localized pages since that will conflict with
the dump loading process. We can also assume that the dump already
contains the localized pages.
This change checks for the `raw` kwarg in the signal handlers and
exists the function if it is True.
> Add a disable_for_loaddata decorator on signals

- src/wagtailtrans/templates/wagtailtrans/templatetags/language_selector.html
In language selector, it is preferable to show languages in their local names.
See https://ux.stackexchange.com/questions/37017/language-of-language-names-in-the-language-selector
> Show languages in their local names.

- .travis.yml
- CHANGELOG.rst
- CONTRIBUTING.md
- Makefile
- README.rst
- docs/source/contributing.rst
- docs/source/releases/2.1.rst
- docs/source/releases/index.rst
- setup.py
- src/wagtailtrans/__init__.py
- src/wagtailtrans/models.py
- src/wagtailtrans/permissions.py
- src/wagtailtrans/signals.py
- src/wagtailtrans/views/translation.py
- src/wagtailtrans/wagtail_hooks.py
- tests/_sandbox/settings/base.py
- tests/factories/pages.py
- tests/factories/sites.py
- tests/fixtures.py
- tests/unit/test_edit_handlers.py
- tests/unit/test_forms.py
- tests/unit/test_middleware.py
- tests/unit/test_models.py
- tests/unit/test_permissions.py
- tests/unit/test_signals.py
- tests/unit/test_sites.py
- tests/unit/test_templatetags.py
- tests/unit/test_views.py
- tox.ini
In order to prepare for Wagtail 2.8 and Django 3.0 we will need another release (#173). As the importing of static has changed. 
- As Django 1.11 is officially supported until april I kept the reference to Wagtail 2.3 intact.
- I cleaned up extra tests in between 2.3 and 2.7 (which I added and is the new LTS)
The current Tox and Travis setup is based upon the combinations which are defined in the overview of compatible Django and Python version as listed in the [documentation](https://docs.wagtail.io/en/latest/releases/upgrading.html#compatible-django-python-versions).
> Add Wagtail 2.7 LTS and 2.8 to the testsuite

- src/wagtailtrans/wagtail_hooks.py
This allows all languages (live or not) to be translated into from the dropdown menu on pages. This will allow admins to create Drafts of pages while the language is still in progress, which Fixes #179.
> Allow page translations into non-live language

- .travis.yml
- CHANGELOG.rst
- README.rst
- setup.py
- src/wagtailtrans/apps.py
- src/wagtailtrans/forms.py
- src/wagtailtrans/models.py
- src/wagtailtrans/permissions.py
- src/wagtailtrans/views/translation.py
- src/wagtailtrans/wagtail_hooks.py
- tests/factories/language.py
- tests/factories/pages.py
- tests/factories/sites.py
- tests/factories/users.py
- tox.ini
- Added official support for Wagtail 2.9 and 2.10
- Make the permission `can_delete` compatible with Wagtail 2.10
- Make the page method `move` compatible with Wagtail 2.10
- Dropped support for Wagtail versions earlier than 2.7 (LTS)
- Replace deprecated ugettext, ugettext_lazy with gettext and gettext_lazy
- Replace deprecated force_text with force_str
Fixes #186
> Make Wagtail 2.10 compatible
